include: package:very_good_analysis/analysis_options.3.0.1.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
