include: package:very_good_analysis/analysis_options.3.0.1.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false
    cascade_invocations: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
